# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(439, 407)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(100, 10, 311, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 71, 31))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 360, 391, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.em3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em3.setMaximumSize(QtCore.QSize(30, 20))
        self.em3.setObjectName("em3")
        self.gridLayout.addWidget(self.em3, 0, 2, 1, 1)
        self.em1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em1.setMaximumSize(QtCore.QSize(30, 20))
        self.em1.setObjectName("em1")
        self.gridLayout.addWidget(self.em1, 0, 0, 1, 1)
        self.em5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em5.setMaximumSize(QtCore.QSize(30, 20))
        self.em5.setObjectName("em5")
        self.gridLayout.addWidget(self.em5, 0, 4, 1, 1)
        self.em9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em9.setMaximumSize(QtCore.QSize(30, 20))
        self.em9.setObjectName("em9")
        self.gridLayout.addWidget(self.em9, 0, 8, 1, 1)
        self.em7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em7.setMaximumSize(QtCore.QSize(30, 20))
        self.em7.setObjectName("em7")
        self.gridLayout.addWidget(self.em7, 0, 6, 1, 1)
        self.em4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em4.setMaximumSize(QtCore.QSize(30, 20))
        self.em4.setObjectName("em4")
        self.gridLayout.addWidget(self.em4, 0, 3, 1, 1)
        self.em8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em8.setMaximumSize(QtCore.QSize(30, 20))
        self.em8.setObjectName("em8")
        self.gridLayout.addWidget(self.em8, 0, 7, 1, 1)
        self.em2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em2.setMaximumSize(QtCore.QSize(30, 20))
        self.em2.setObjectName("em2")
        self.gridLayout.addWidget(self.em2, 0, 1, 1, 1)
        self.em6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em6.setMaximumSize(QtCore.QSize(30, 20))
        self.em6.setObjectName("em6")
        self.gridLayout.addWidget(self.em6, 0, 5, 1, 1)
        self.em10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.em10.setMaximumSize(QtCore.QSize(30, 20))
        self.em10.setText("")
        self.em10.setObjectName("em10")
        self.gridLayout.addWidget(self.em10, 0, 9, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(370, 280, 51, 71))
        self.pushButton.setObjectName("pushButton")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 280, 331, 70))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QTextEdit(Form)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 381, 211))
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Nombre:"))
        self.em3.setText(_translate("Form", "PushButton"))
        self.em1.setText(_translate("Form", "PushButton"))
        self.em5.setText(_translate("Form", "PushButton"))
        self.em9.setText(_translate("Form", "PushButton"))
        self.em7.setText(_translate("Form", "PushButton"))
        self.em4.setText(_translate("Form", "PushButton"))
        self.em8.setText(_translate("Form", "PushButton"))
        self.em2.setText(_translate("Form", "PushButton"))
        self.em6.setText(_translate("Form", "PushButton"))
        self.pushButton.setText(_translate("Form", ">>>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
